/// 이모지 내장 카탈로그 — 자주 쓰는 것 위주로 한/영 키워드를 붙여 검색한다.
enum EmojiCatalog {
    struct Entry {
        let emoji: String
        let name: String        // 표시 이름 (한국어)
        let keywords: [String]  // fuzzy 매칭 대상 (한/영)
    }

    private static func E(_ emoji: String, _ name: String, _ keywords: String) -> Entry {
        Entry(emoji: emoji, name: name, keywords: keywords.split(separator: " ").map(String.init) + [name])
    }

    static let all: [Entry] = [
        // 표정
        E("😀", "활짝 웃음", "grinning smile happy 웃음 미소 행복"),
        E("😂", "기쁨의 눈물", "joy tears lol 웃겨 눈물 ㅋㅋ"),
        E("🤣", "데굴데굴 웃음", "rofl laughing 포복절도 웃음"),
        E("😊", "수줍은 미소", "blush smile 수줍 미소 방긋"),
        E("😍", "하트 눈", "heart eyes love 사랑 하트눈 반함"),
        E("🥰", "사랑스러움", "love hearts adore 사랑 애정"),
        E("😘", "키스", "kiss 뽀뽀 키스"),
        E("😎", "선글라스", "cool sunglasses 멋짐 쿨 선글라스"),
        E("🤔", "고민", "thinking 생각 고민 흠"),
        E("😅", "진땀 웃음", "sweat smile 진땀 식은땀 허허"),
        E("😢", "훌쩍", "cry sad tear 슬픔 눈물 훌쩍"),
        E("😭", "엉엉", "sob crying loudly 엉엉 대성통곡 눈물"),
        E("😡", "화남", "angry rage mad 화남 분노 빡침"),
        E("😱", "비명", "scream shocked 비명 충격 놀람"),
        E("😴", "잠", "sleep zzz 잠 졸림 수면"),
        E("🥱", "하품", "yawn tired 하품 피곤"),
        E("😷", "마스크", "mask sick 마스크 아픔 감기"),
        E("🤒", "체온계", "sick fever thermometer 아픔 열 몸살"),
        E("🤗", "포옹", "hug 포옹 안아줘"),
        E("🙄", "눈 굴리기", "eye roll 눈굴리기 어이없음"),
        E("😳", "당황", "flushed 당황 얼굴빨개짐 부끄"),
        E("🥲", "웃픔", "smiling tear 웃픔 씁쓸"),
        E("🤩", "별 눈", "star struck 별눈 감탄 대박"),
        E("😇", "천사", "innocent angel halo 천사 순수"),
        E("🤯", "머리 폭발", "mind blown exploding head 충격 멘붕"),
        E("🥳", "파티 얼굴", "party celebrate 파티 축하 생일"),
        E("😤", "씩씩", "huff triumph 씩씩 콧김 분함"),
        E("🤫", "쉿", "shush quiet secret 쉿 조용 비밀"),
        E("🤮", "구토", "vomit 구토 웩 역겨움"),
        E("🙃", "거꾸로 웃음", "upside down 거꾸로 능청"),
        E("😐", "무표정", "neutral 무표정 노잼 뚱"),
        E("🤪", "익살", "zany crazy 익살 장난 미침"),
        E("🫠", "녹는 얼굴", "melting 녹음 힘듦 데워짐"),
        E("😈", "악마 미소", "devil smiling imp 악마 음흉"),
        E("💀", "해골", "skull dead 해골 죽음 ㅋㅋ"),
        E("🤡", "광대", "clown 광대 삐에로"),
        E("👻", "유령", "ghost 유령 귀신"),
        E("👽", "외계인", "alien 외계인 우주인"),
        E("🤖", "로봇", "robot 로봇 봇"),
        E("💩", "응가", "poop 응가 똥"),
        // 손
        E("👍", "따봉", "thumbs up good like 좋아요 따봉 최고 굿"),
        E("👎", "비추", "thumbs down bad 싫어요 비추 별로"),
        E("👏", "박수", "clap applause 박수 짝짝"),
        E("🙏", "부탁·감사", "pray please thanks 기도 부탁 감사 제발"),
        E("👌", "오케이", "ok okay perfect 오케이 완벽"),
        E("✌️", "브이", "victory peace 브이 평화"),
        E("🤞", "행운", "crossed fingers luck 행운 손가락 꼬기"),
        E("👋", "인사", "wave hello bye 인사 손흔들기 안녕"),
        E("🤝", "악수", "handshake deal 악수 협력 계약"),
        E("💪", "근육", "muscle strong 근육 힘 화이팅 운동"),
        E("🙌", "만세", "raised hands hooray 만세 환호"),
        E("👉", "오른쪽 가리킴", "point right 가리킴 오른쪽"),
        E("👈", "왼쪽 가리킴", "point left 가리킴 왼쪽"),
        E("☝️", "위 가리킴", "point up 가리킴 위"),
        E("👇", "아래 가리킴", "point down 가리킴 아래"),
        E("✊", "주먹", "fist 주먹 파이팅"),
        E("🤙", "전화 손짓", "call me shaka 전화 콜"),
        E("🖐️", "손바닥", "hand palm five 손바닥 하이파이브"),
        E("✍️", "쓰기", "writing hand 쓰기 필기 서명"),
        E("🫶", "손하트", "heart hands 손하트 사랑"),
        // 하트·감정
        E("❤️", "빨간 하트", "red heart love 하트 사랑 빨강"),
        E("🧡", "주황 하트", "orange heart 주황 하트"),
        E("💛", "노란 하트", "yellow heart 노랑 하트"),
        E("💚", "초록 하트", "green heart 초록 하트"),
        E("💙", "파란 하트", "blue heart 파랑 하트"),
        E("💜", "보라 하트", "purple heart 보라 하트"),
        E("🖤", "검은 하트", "black heart 검정 하트"),
        E("🤍", "하얀 하트", "white heart 하양 흰 하트"),
        E("💕", "두 하트", "two hearts 하트 두개 사랑"),
        E("💖", "반짝 하트", "sparkling heart 반짝 하트"),
        E("💔", "상심", "broken heart 이별 상심 하트 깨짐"),
        E("💗", "커지는 하트", "growing heart 하트 두근"),
        E("💯", "백점", "hundred perfect 백점 100 완벽"),
        E("💢", "화남 표시", "anger symbol 화남 빠직"),
        E("💥", "폭발", "boom collision 폭발 쾅 충돌"),
        E("💦", "땀방울", "sweat droplets 땀 물방울"),
        E("💤", "쿨쿨", "zzz sleep 잠 쿨쿨"),
        // 동물
        E("🐶", "강아지", "dog puppy 강아지 개 멍멍"),
        E("🐱", "고양이", "cat kitty 고양이 냥이 야옹"),
        E("🐭", "쥐", "mouse 쥐 생쥐"),
        E("🐹", "햄스터", "hamster 햄스터"),
        E("🐰", "토끼", "rabbit bunny 토끼"),
        E("🦊", "여우", "fox 여우"),
        E("🐻", "곰", "bear 곰"),
        E("🐼", "판다", "panda 판다 팬더"),
        E("🐯", "호랑이", "tiger 호랑이 범"),
        E("🦁", "사자", "lion 사자"),
        E("🐮", "소", "cow 소 젖소"),
        E("🐷", "돼지", "pig 돼지"),
        E("🐸", "개구리", "frog 개구리"),
        E("🐵", "원숭이", "monkey 원숭이"),
        E("🐔", "닭", "chicken 닭 꼬꼬"),
        E("🐧", "펭귄", "penguin 펭귄"),
        E("🐦", "새", "bird 새"),
        E("🦅", "독수리", "eagle 독수리"),
        E("🦉", "부엉이", "owl 부엉이 올빼미"),
        E("🐺", "늑대", "wolf 늑대"),
        E("🐴", "말", "horse 말"),
        E("🦄", "유니콘", "unicorn 유니콘"),
        E("🐝", "벌", "bee 벌 꿀벌"),
        E("🦋", "나비", "butterfly 나비"),
        E("🐢", "거북이", "turtle 거북 거북이"),
        E("🐍", "뱀", "snake 뱀"),
        E("🐙", "문어", "octopus 문어"),
        E("🦀", "게", "crab 게 꽃게"),
        E("🐬", "돌고래", "dolphin 돌고래"),
        E("🐳", "고래", "whale 고래"),
        E("🦈", "상어", "shark 상어"),
        E("🐟", "물고기", "fish 물고기 생선"),
        // 음식
        E("🍎", "사과", "apple 사과"),
        E("🍌", "바나나", "banana 바나나"),
        E("🍉", "수박", "watermelon 수박"),
        E("🍇", "포도", "grapes 포도"),
        E("🍓", "딸기", "strawberry 딸기"),
        E("🍑", "복숭아", "peach 복숭아"),
        E("🍒", "체리", "cherries 체리 앵두"),
        E("🍅", "토마토", "tomato 토마토"),
        E("🥑", "아보카도", "avocado 아보카도"),
        E("🍞", "식빵", "bread 빵 식빵"),
        E("🧀", "치즈", "cheese 치즈"),
        E("🍔", "햄버거", "hamburger burger 햄버거 버거"),
        E("🍟", "감자튀김", "fries 감자튀김 감튀"),
        E("🍕", "피자", "pizza 피자"),
        E("🌭", "핫도그", "hot dog 핫도그"),
        E("🍗", "치킨", "chicken drumstick 치킨 닭다리"),
        E("🍜", "라면", "ramen noodle 라면 국수 면"),
        E("🍚", "밥", "rice 밥 쌀밥"),
        E("🍙", "주먹밥", "rice ball onigiri 주먹밥 삼각김밥"),
        E("🍣", "초밥", "sushi 초밥 스시"),
        E("🍤", "새우튀김", "shrimp fried 새우튀김 새우"),
        E("🥟", "만두", "dumpling 만두"),
        E("🍦", "아이스크림", "ice cream 아이스크림"),
        E("🍰", "케이크", "cake 케이크 조각케이크"),
        E("🎂", "생일 케이크", "birthday cake 생일 케이크 축하"),
        E("🍫", "초콜릿", "chocolate 초콜릿 초코"),
        E("🍬", "사탕", "candy 사탕 캔디"),
        E("🍩", "도넛", "donut 도넛"),
        E("🍪", "쿠키", "cookie 쿠키 과자"),
        E("☕", "커피", "coffee 커피 아메리카노"),
        E("🍵", "차", "tea 차 녹차"),
        E("🥤", "음료", "cup straw 음료 콜라 음료수"),
        E("🍺", "맥주", "beer 맥주 호프"),
        E("🍻", "건배", "cheers beers 건배 짠"),
        E("🍷", "와인", "wine 와인 포도주"),
        E("🥃", "위스키", "whisky tumbler 위스키 양주"),
        E("🍶", "사케", "sake 사케 정종 술"),
        // 활동·사물
        E("⚽", "축구공", "soccer football 축구 축구공"),
        E("⚾", "야구공", "baseball 야구 야구공"),
        E("🏀", "농구공", "basketball 농구 농구공"),
        E("🎾", "테니스", "tennis 테니스"),
        E("🏸", "배드민턴", "badminton 배드민턴"),
        E("🏋️", "역도", "weight lifting 헬스 역도 운동"),
        E("🏃", "달리기", "running 달리기 러닝 조깅"),
        E("🚴", "자전거 타기", "cycling 자전거 라이딩"),
        E("⛳", "골프", "golf 골프 깃발"),
        E("🎮", "게임", "video game controller 게임 게임패드"),
        E("🎲", "주사위", "dice 주사위 보드게임"),
        E("🎯", "과녁", "dart target 과녁 다트 목표"),
        E("🎤", "마이크", "microphone 마이크 노래 노래방"),
        E("🎧", "헤드폰", "headphone 헤드폰 음악감상"),
        E("🎵", "음표", "music note 음표 음악"),
        E("🎸", "기타", "guitar 기타"),
        E("🎹", "피아노", "piano keyboard 피아노 건반"),
        E("🎨", "팔레트", "art palette 미술 그림 팔레트"),
        E("🎬", "클래퍼보드", "movie clapper 영화 촬영"),
        E("📷", "카메라", "camera 카메라 사진"),
        E("🎁", "선물", "gift present 선물"),
        E("🎈", "풍선", "balloon 풍선 파티"),
        E("🎉", "폭죽", "party popper tada 축하 폭죽 파티 짜잔"),
        E("🎊", "색종이", "confetti 색종이 축하"),
        E("🏆", "트로피", "trophy 트로피 우승 1등"),
        E("🥇", "금메달", "gold medal 금메달 1등"),
        E("🥈", "은메달", "silver medal 은메달 2등"),
        E("🥉", "동메달", "bronze medal 동메달 3등"),
        // 사무·기술
        E("💻", "노트북", "laptop computer 노트북 컴퓨터 맥북"),
        E("🖥️", "데스크탑", "desktop computer 데스크탑 모니터"),
        E("⌨️", "키보드", "keyboard 키보드"),
        E("🖱️", "마우스", "mouse computer 마우스"),
        E("📱", "스마트폰", "phone mobile 휴대폰 폰 아이폰"),
        E("📞", "전화", "telephone call 전화 통화"),
        E("📧", "이메일", "email mail 이메일 메일"),
        E("📅", "달력", "calendar 달력 일정 캘린더"),
        E("📌", "핀", "pin pushpin 핀 고정"),
        E("📎", "클립", "paperclip 클립"),
        E("✏️", "연필", "pencil 연필 필기"),
        E("📝", "메모", "memo note 메모 노트 작성"),
        E("📚", "책", "books 책 공부 독서"),
        E("📖", "펼친 책", "open book 책 읽기"),
        E("🔍", "돋보기", "magnifying glass search 검색 돋보기"),
        E("🔒", "자물쇠", "lock 잠금 자물쇠 보안"),
        E("🔓", "열린 자물쇠", "unlock 잠금해제 열림"),
        E("🔑", "열쇠", "key 열쇠 키"),
        E("🔔", "종", "bell notification 알림 종"),
        E("💡", "전구", "bulb idea 아이디어 전구"),
        E("🔋", "배터리", "battery 배터리 충전"),
        E("🔌", "플러그", "plug 플러그 전원 콘센트"),
        E("🛠️", "공구", "tools hammer wrench 공구 수리 도구"),
        E("⚙️", "톱니바퀴", "gear settings 설정 톱니"),
        E("🧲", "자석", "magnet 자석"),
        E("💰", "돈주머니", "money bag 돈 부자 재물"),
        E("💵", "지폐", "dollar money 돈 지폐 달러"),
        E("💳", "카드", "credit card 카드 결제"),
        E("📈", "상승 차트", "chart up 상승 주가 증가 그래프"),
        E("📉", "하락 차트", "chart down 하락 감소 그래프"),
        E("📊", "막대 차트", "bar chart 차트 그래프 통계"),
        // 이동·장소
        E("🚗", "자동차", "car 자동차 차"),
        E("🚕", "택시", "taxi 택시"),
        E("🚌", "버스", "bus 버스"),
        E("🚇", "지하철", "metro subway 지하철 전철"),
        E("🚄", "고속열차", "train ktx 기차 열차 케이티엑스"),
        E("✈️", "비행기", "airplane 비행기 여행 항공"),
        E("🚀", "로켓", "rocket 로켓 발사 출시"),
        E("🚢", "배", "ship 배 선박 크루즈"),
        E("🏠", "집", "house home 집 홈"),
        E("🏢", "빌딩", "office building 회사 빌딩 사무실"),
        E("🏥", "병원", "hospital 병원"),
        E("🏦", "은행", "bank 은행"),
        E("🏫", "학교", "school 학교"),
        E("⛰️", "산", "mountain 산 등산"),
        E("🏖️", "해변", "beach 해변 바닷가 휴가"),
        E("🗼", "타워", "tower 타워 탑"),
        // 자연·날씨
        E("☀️", "해", "sun sunny 해 맑음 태양"),
        E("🌙", "달", "moon 달 밤"),
        E("⭐", "별", "star 별"),
        E("🌟", "빛나는 별", "glowing star 반짝 별"),
        E("✨", "반짝임", "sparkles 반짝 빤짝 이쁨"),
        E("☁️", "구름", "cloud 구름 흐림"),
        E("🌧️", "비", "rain 비 우천"),
        E("⛈️", "뇌우", "thunderstorm 천둥 번개 폭풍"),
        E("❄️", "눈송이", "snowflake 눈 눈송이 겨울"),
        E("🌈", "무지개", "rainbow 무지개"),
        E("🔥", "불", "fire hot lit 불 화재 핫 불꽃"),
        E("💧", "물방울", "droplet water 물 물방울"),
        E("🌊", "파도", "wave ocean 파도 바다"),
        E("🌸", "벚꽃", "cherry blossom 벚꽃 봄"),
        E("🌹", "장미", "rose 장미 꽃"),
        E("🌻", "해바라기", "sunflower 해바라기"),
        E("🌷", "튤립", "tulip 튤립 꽃"),
        E("🍀", "네잎클로버", "clover luck 클로버 행운"),
        E("🌲", "나무", "tree evergreen 나무 소나무"),
        E("🌵", "선인장", "cactus 선인장"),
        // 기호
        E("✅", "체크", "check done ok 체크 완료 확인"),
        E("❌", "엑스", "cross x no 엑스 취소 아니오 금지"),
        E("⭕", "동그라미", "circle o 동그라미 맞음"),
        E("❗", "느낌표", "exclamation 느낌표 주의"),
        E("❓", "물음표", "question 물음표 질문"),
        E("⚠️", "경고", "warning 경고 주의"),
        E("🚫", "금지", "prohibited no 금지 안됨"),
        E("♻️", "재활용", "recycle 재활용"),
        E("🔴", "빨간 원", "red circle 빨강 원"),
        E("🟢", "초록 원", "green circle 초록 원"),
        E("🔵", "파란 원", "blue circle 파랑 원"),
        E("🟡", "노란 원", "yellow circle 노랑 원"),
        E("➡️", "오른쪽 화살표", "right arrow 화살표 오른쪽"),
        E("⬅️", "왼쪽 화살표", "left arrow 화살표 왼쪽"),
        E("⬆️", "위 화살표", "up arrow 화살표 위"),
        E("⬇️", "아래 화살표", "down arrow 화살표 아래"),
        E("🔄", "새로고침", "refresh reload 새로고침 갱신 순환"),
        E("➕", "더하기", "plus add 더하기 추가"),
        E("➖", "빼기", "minus 빼기 제거"),
        E("💲", "달러 기호", "dollar sign 달러"),
        E("©️", "저작권", "copyright 저작권 카피라이트"),
        E("🔞", "19금", "18 adults 성인 19금"),
        // 시간·국기
        E("⏰", "알람시계", "alarm clock 알람 시계"),
        E("⏳", "모래시계", "hourglass 모래시계 대기"),
        E("⌛", "모래시계 끝", "hourglass done 모래시계 종료"),
        E("🕐", "1시", "clock one 시계 한시"),
        E("🇰🇷", "태극기", "korea flag 한국 태극기 대한민국"),
        E("🇺🇸", "성조기", "usa flag america 미국 성조기"),
        E("🇯🇵", "일장기", "japan flag 일본 일장기"),
        E("🇨🇳", "오성홍기", "china flag 중국"),
        E("🇬🇧", "유니언잭", "uk britain flag 영국"),
        E("🇫🇷", "삼색기", "france flag 프랑스"),
        E("🇩🇪", "독일 국기", "germany flag 독일"),
    ]
}
